### ISSUE TITLE
where can i download this plugin?

### ISSUE THREAD

**Issue by chickiyeah** [EncryptSL/HideAndSeek#2]
where can i download this plugin?
pls give me link

**Comment by EncryptSL** [comment]
#1 
This is only fork, with support for 1.13, official build is on [Link for Official build](https://dev.bukkit.org/projects/blockhunt/files)

**Comment by EncryptSL** [comment]
#1 Download Link for 1.13, 

This is only basic fork with support 1.13 this plugin need more bugfixes and i don't know what everythink. [Official Build without support](https://dev.bukkit.org/projects/blockhunt/files)
